name: TuxCare VEX Auto-Triage

on:
  workflow_dispatch:      # Manual trigger

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
      - name: Run TuxCare VEX Auto-Triage
        uses: cloudlinux/vex-triage@v1
        with:
          ecosystems: 'java'
          token: ${{ secrets.PERSONAL_TOKEN }}
          dry-run: 'true'
