name: TuxCare VEX Auto-Triage

on:
#   schedule:
#     - cron: '0 2 * * *'  # Daily at 2 AM
  workflow_dispatch:      # Manual trigger

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
      - name: Run TuxCare VEX Auto-Triage
        uses: anayden/tuxcare-workflow@main
        with:
          ecosystems: 'java'
          token: ${{ secrets.GITHUB_TOKEN }}
          verbosity: 'DEBUG'
